//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWorkDemo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Id { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public Nullable<int> DiscountTo { get; set; }
        public Nullable<int> DiscountCodeId { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
