//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWorkDemo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.Carts = new HashSet<Cart>();
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int Id { get; set; }
        public string CourseName { get; set; }
        public string CourseShortDesc { get; set; }
        public string CourseDesc { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> IsShowOnSite { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<OrderLine> OrderLines { get; set; }
    }
}
